language: java

sudo: required
dist: trusty
group: edge

before_install:
  - chmod +x gradlew
  - mkdir -p ~/.gradle && echo "org.gradle.daemon=false" >> ~/.gradle/gradle.properties
  - export GRADLE_OPTS=-Xmx1024m
  - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh
  - wget https://download.java.net/java/early_access/loom/6/openjdk-16-loom+6-105_linux-x64_bin.tar.gz
  - tar -zxvf openjdk-16-loom+6-105_linux-x64_bin.tar.gz
  - export LOOM_JDK=jdk-16
  - chmod +x install-jdk.sh
  - . ./install-jdk.sh -F 12 -L GPL

after_success:
  - bash <(curl -s https://codecov.io/bash)

# prevent travis running gradle assemble; let the build script do it anyway
install: true

script:
  - echo PATH = ${PATH}
  - echo JAVA_HOME = ${JAVA_HOME}
  - java -version
  - ./gradlew build --stacktrace

 # cache between builds
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle
